modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC-BY-4.0"

[[mods]]
modId = "ftbqlocalkeys"
version = "${version}"
displayName = "FTBQLocalizationKeys-Reconverted"
displayURL="https://github.com/LocalizedMC/FTBQLocalizationkeys"
logoFile="icon.png" #optional
credits="BlackAuresArt"
authors="TexTrue, LocalizedMC, BocchiKessokuTeam"
description = '''
FTB Quest lang converter
'''

[[dependencies.ftbqlocalkeys]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqlocalkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqlocalkeys]]
modId = "ftbquests"
mandatory = true
versionRange = "[1902,)"
ordering = "NONE"
side = "BOTH"
